package com.Meal.MealDb.client;

import com.fasterxml.jackson.annotation.JsonProperty;

public record TheMealDbMeal(
        @JsonProperty("idMeal") String idMeal,
        @JsonProperty("strMeal") String strMeal,
        @JsonProperty("strCategory") String strCategory,
        @JsonProperty("strArea") String strArea,
        @JsonProperty("strMealThumb") String strMealThumb,
        @JsonProperty("strTags") String strTags,
        @JsonProperty("strInstructions") String strInstructions,
        @JsonProperty("strYoutube") String strYoutube,
        @JsonProperty("strIngredient1") String strIngredient1,
        @JsonProperty("strIngredient2") String strIngredient2,
        @JsonProperty("strIngredient3") String strIngredient3,
        @JsonProperty("strIngredient4") String strIngredient4,
        @JsonProperty("strIngredient5") String strIngredient5,
        @JsonProperty("strIngredient6") String strIngredient6,
        @JsonProperty("strIngredient7") String strIngredient7,
        @JsonProperty("strIngredient8") String strIngredient8,
        @JsonProperty("strIngredient9") String strIngredient9,
        @JsonProperty("strIngredient10") String strIngredient10,
        @JsonProperty("strIngredient11") String strIngredient11,
        @JsonProperty("strIngredient12") String strIngredient12,
        @JsonProperty("strIngredient13") String strIngredient13,
        @JsonProperty("strIngredient14") String strIngredient14,
        @JsonProperty("strIngredient15") String strIngredient15,
        @JsonProperty("strIngredient16") String strIngredient16,
        @JsonProperty("strIngredient17") String strIngredient17,
        @JsonProperty("strIngredient18") String strIngredient18,
        @JsonProperty("strIngredient19") String strIngredient19,
        @JsonProperty("strIngredient20") String strIngredient20,
        @JsonProperty("strMeasure1") String strMeasure1,
        @JsonProperty("strMeasure2") String strMeasure2,
        @JsonProperty("strMeasure3") String strMeasure3,
        @JsonProperty("strMeasure4") String strMeasure4,
        @JsonProperty("strMeasure5") String strMeasure5,
        @JsonProperty("strMeasure6") String strMeasure6,
        @JsonProperty("strMeasure7") String strMeasure7,
        @JsonProperty("strMeasure8") String strMeasure8,
        @JsonProperty("strMeasure9") String strMeasure9,
        @JsonProperty("strMeasure10") String strMeasure10,
        @JsonProperty("strMeasure11") String strMeasure11,
        @JsonProperty("strMeasure12") String strMeasure12,
        @JsonProperty("strMeasure13") String strMeasure13,
        @JsonProperty("strMeasure14") String strMeasure14,
        @JsonProperty("strMeasure15") String strMeasure15,
        @JsonProperty("strMeasure16") String strMeasure16,
        @JsonProperty("strMeasure17") String strMeasure17,
        @JsonProperty("strMeasure18") String strMeasure18,
        @JsonProperty("strMeasure19") String strMeasure19,
        @JsonProperty("strMeasure20") String strMeasure20) {
}
